---
name: Lint

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: seventhlab/github-actions/actions/checkout@v1.5.0

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
