---
name: "Checks, linters and formatters"

on:
  workflow_call:
    inputs:
      pnpm-version:
        description: 'Version of pnpm to use. Default is 10.'
        type: number
        required: false
        default: 10
      node-version:
        description: 'Version of Node.js to use. Default is 24.'
        type: number
        required: false
        default: 24
      go-version:
        description: 'Version of Go to use. Default is 1.26.x.'
        type: string
        required: false
        default: '1.26.x'
      use-github-npm-registry:
        description: 'Whether to use GitHub npm registry. Default is true.'
        type: boolean
        required: false
        default: true
      use-github-go-repository:
        description: 'Whether to use GitHub Go repository for private modules. Default is true.'
        type: boolean
        required: false
        default: true
      use-node:
        description: 'Whether to set up Node.js environment. Default is true.'
        type: boolean
        required: false
        default: true
      use-go:
        description: 'Whether to set up Go environment. Default is true.'
        type: boolean
        required: false
        default: true
    secrets:
      NODE_AUTH_TOKEN:
        description: 'GitHub npm registry authentication token. Required if `use-github-npm-registry` is true.'
        required: false
      GO_PRIVATE_TOKEN:
        description: 'GitHub Go repository authentication token. Required if `use-github-go-repository` is true.'
        required: false

jobs:
  lint:
    name: Pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: seventhlab/github-actions/actions/checkout@v1.5.0

      - name: Setup node
        uses: seventhlab/github-actions/actions/setup-node@v1.5.0
        if: ${{ inputs.use-node }}
        with:
          pnpm-version: ${{ inputs.pnpm-version }}
          node-version: ${{ inputs.node-version }}
          use-github-npm-registry: ${{ inputs.use-github-npm-registry }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install node dependencies
        if: ${{ inputs.use-node }}
        run: |
          pnpm install

      - name: Setup Go
        uses: seventhlab/github-actions/actions/setup-go@v1.5.0
        if: ${{ inputs.use-go }}
        with:
          go-version: ${{ inputs.go-version }}
          use-github-go-repository: ${{ inputs.use-github-go-repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GO_PRIVATE_TOKEN }}

      - name: Install Go dependencies
        if: ${{ inputs.use-go }}
        run: |
          go mod download

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.1
