name: Wait for CI
on:
  pull_request:
    branches:
      - main

jobs:
  wait-for-ci:
    name: Wait for CI
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI
        uses: seventhlab/github-actions/actions/wait-for-ci@v1.4.0
        with:
          commitSha: ${{ github.event.pull_request.head.sha }}
          jobName: "Wait for CI"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
